import os
from datetime import datetime
from pathlib import Path
from src.generate_sql_inserts import generate_sql_inserts
from src.config import VERBOSE

banner = """
-- SQL generated by wms-data-generator
-- DO NOT EDIT THIS FILE MANUALLY
-- Edit the create-wms-schema.sql file instead
--
-- 🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚
-- 🚚 DELIVEROO (C) 2025 🚚
-- 🚚   SHIP THAT SHIT   🚚
-- 🚚   Spółka Akcyjna   🚚
-- 🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚
--
-- Zatrudniamy! https://shorturl.at/G98Ej
"""

def create_sql_file():
    # Get the project root directory (wms-data-generator)
    # This file is in src/, so go up one level
    project_root = Path(__file__).parent.parent
    
    schema_path = project_root / "schema" / "create-wms-schema.sql"
    with open(schema_path, "r", encoding="utf-8") as schema_file:
        create_table_sql = schema_file.read()

    output_dir = project_root / "output"
    os.makedirs(output_dir, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d-%H%M%S")
    filename = f"wms-{timestamp}.sql"
    filepath = output_dir / filename

    # Generate SQL and stats
    result = generate_sql_inserts()
    sql_script = (
        banner
        + "\n\n"
        + create_table_sql.strip()
        + "\n\n"
        + "\n".join(result.lines)
    )
    stats = result.stats

    if VERBOSE:
        print("- Saving output...", end="", flush=True)
    
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(sql_script)
    
    if VERBOSE:
        print(" done")

    print(f"Generated insert statements in {filepath}")
    print("\nFollowing records have been created:")
    for table, count in stats.items():
        print(f"- {table}: {count}") 