import { Expense } from './expense.model';

// Mock data
export const mockExpenses: Expense[] = [
  {
    id: 'EXP001',
    date: '2025-01-15',
    expenseType: 'Fuel',
    category: 'Variable',
    amount: 1200,
    currency: 'PLN',
    status: 'Approved',
    transporter: 'John Smith',
    vehicle: 'TRK-123',
    trip: 'Warsaw-Berlin',
    odometer: 120000,
    notes: 'Night refill at highway station',
    vendor: 'Orlen',
    invoiceNumber: 'INV-2025-001',
    paymentDueDate: '2025-01-30',
    paymentStatus: 'Paid',
    recurrence: false,
    attachments: ['receipt.pdf']
  },
  {
    id: 'EXP002',
    date: '2025-01-14',
    expenseType: 'Maintenance',
    category: 'Fixed',
    amount: 2400,
    currency: 'PLN',
    status: 'Pending',
    transporter: 'Mike Brown',
    vehicle: 'TRK-456',
    trip: '',
    odometer: 90000,
    notes: 'Brake pads replacement',
    vendor: 'Bosch Service',
    invoiceNumber: 'BSC-2025-045',
    paymentDueDate: '2025-02-15',
    paymentStatus: 'Unpaid',
    recurrence: false,
    attachments: ['invoice.pdf', 'photo.jpg']
  },
  {
    id: 'EXP003',
    date: '2025-01-13',
    expenseType: 'Insurance',
    category: 'Fixed',
    amount: 3500,
    currency: 'PLN',
    status: 'Approved',
    transporter: 'Fleet Manager',
    vehicle: 'ALL',
    trip: '',
    odometer: 0,
    notes: 'Monthly fleet insurance premium',
    vendor: 'PZU Insurance',
    invoiceNumber: 'PZU-2025-001',
    paymentDueDate: '2025-01-31',
    paymentStatus: 'Paid',
    recurrence: true,
    attachments: ['policy.pdf']
  },
  {
    id: 'EXP004',
    date: '2025-01-12',
    expenseType: 'Toll',
    category: 'Variable',
    amount: 150,
    currency: 'PLN',
    status: 'Approved',
    transporter: 'Sarah Lee',
    vehicle: 'TRK-789',
    trip: 'Krakow-Prague',
    odometer: 85000,
    notes: 'Highway tolls A4',
    vendor: 'GDDKiA',
    invoiceNumber: 'TOLL-2025-012',
    paymentDueDate: '2025-01-25',
    paymentStatus: 'Paid',
    recurrence: false,
    attachments: ['toll_receipt.pdf']
  },
  {
    id: 'EXP005',
    date: '2025-01-11',
    expenseType: 'Repairs',
    category: 'Variable',
    amount: 1800,
    currency: 'PLN',
    status: 'Rejected',
    transporter: 'David Chen',
    vehicle: 'TRK-321',
    trip: '',
    odometer: 110000,
    notes: 'Engine diagnostic - not covered under warranty',
    vendor: 'AutoService Plus',
    invoiceNumber: 'ASP-2025-078',
    paymentDueDate: '2025-02-10',
    paymentStatus: 'Unpaid',
    recurrence: false,
    attachments: ['diagnostic_report.pdf']
  },
  {
    id: 'EXP006',
    date: '2025-01-10',
    expenseType: 'Salary',
    category: 'Administrative',
    amount: 8500,
    currency: 'PLN',
    status: 'Approved',
    transporter: 'HR Department',
    vehicle: '',
    trip: '',
    odometer: 0,
    notes: 'Monthly driver salaries',
    vendor: 'Internal',
    invoiceNumber: 'SAL-2025-001',
    paymentDueDate: '2025-01-31',
    paymentStatus: 'Paid',
    recurrence: true,
    attachments: ['payroll.pdf']
  },
  {
    id: 'EXP007',
    date: '2025-01-09',
    expenseType: 'Accommodation',
    category: 'Operational',
    amount: 450,
    currency: 'EUR',
    status: 'Approved',
    transporter: 'Alex Rodriguez',
    vehicle: 'TRK-654',
    trip: 'Berlin-Amsterdam',
    odometer: 95000,
    notes: 'Overnight stay in Hamburg',
    vendor: 'Hotel Europa',
    invoiceNumber: 'HE-2025-234',
    paymentDueDate: '2025-01-20',
    paymentStatus: 'Paid',
    recurrence: false,
    attachments: ['hotel_receipt.pdf']
  },
  {
    id: 'EXP008',
    date: '2025-01-08',
    expenseType: 'Tires',
    category: 'Variable',
    amount: 3200,
    currency: 'PLN',
    status: 'Pending',
    transporter: 'Lisa Park',
    vehicle: 'TRK-987',
    trip: '',
    odometer: 130000,
    notes: 'Winter tire replacement set',
    vendor: 'Michelin Center',
    invoiceNumber: 'MC-2025-156',
    paymentDueDate: '2025-02-08',
    paymentStatus: 'Unpaid',
    recurrence: false,
    attachments: ['tire_invoice.pdf', 'installation_photo.jpg']
  }
];
