# coding: utf-8

"""
    WMS API (Warehouse Management System)

    API for managing contractors and storage requests

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SpecialRequirement(str, Enum):
    """
    SpecialRequirement
    """

    """
    allowed enum values
    """
    REQUIRED_REFRIGERATION = 'REQUIRED_REFRIGERATION'
    REQUIRED_FREEZING = 'REQUIRED_FREEZING'
    CONTAINS_HAZMAT = 'CONTAINS_HAZMAT'
    CONTAINS_PERISHABLES = 'CONTAINS_PERISHABLES'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SpecialRequirement from a JSON string"""
        return cls(json.loads(json_str))


