/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WMS API (Warehouse Management System)
 * API for managing contractors and storage requests
 * OpenAPI spec version: 1.0.0
 */

export interface AddressDetails {
  address_id?: string;
  street_address?: string;
  city?: string;
  country?: string;
  postal_code?: string;
  address_type?: string;
}
