/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WMS API (Warehouse Management System)
 * API for managing contractors and storage requests
 * OpenAPI spec version: 1.0.0
 */
import type { ContractorStatus } from './contractorStatus';
import type { Contact } from './contact';
import type { AddressDetails } from './addressDetails';
import type { EmployeeSummary } from './employeeSummary';

export interface ContractorDetails {
  id: string;
  name: string;
  status: ContractorStatus;
  /** @nullable */
  tax_id_number?: string;
  created_at?: string;
  updated_at?: string;
  contacts: Contact[];
  addresses: AddressDetails[];
  employees: EmployeeSummary[];
}
