/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WMS API (Warehouse Management System)
 * API for managing contractors and storage requests
 * OpenAPI spec version: 1.0.0
 */
import type { ContractorStatus } from './contractorStatus';
import type { Contact } from './contact';

export interface ContractorSummary {
  id: string;
  name: string;
  status: ContractorStatus;
  /** @nullable */
  tax_id_number?: string;
  contacts: Contact[];
}
