/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WMS API (Warehouse Management System)
 * API for managing contractors and storage requests
 * OpenAPI spec version: 1.0.0
 */
import type { EmployeeSummaryEmployeeData } from './employeeSummaryEmployeeData';
import type { Contact } from './contact';

export interface EmployeeSummary {
  employee_id?: string;
  employee_name?: string;
  employee_data?: EmployeeSummaryEmployeeData;
  contacts?: Contact[];
}
