/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WMS API (Warehouse Management System)
 * API for managing contractors and storage requests
 * OpenAPI spec version: 1.0.0
 */
import type { StorageRequestSummaryCargo } from './storageRequestSummaryCargo';
import type { StorageRequestStatus } from './storageRequestStatus';

export interface StorageRequestSummary {
  id?: string;
  contractorId?: string;
  contractorName?: string;
  cargo?: StorageRequestSummaryCargo;
  entryDate?: string;
  exitDate?: string;
  status?: StorageRequestStatus;
}
