/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WMS API (Warehouse Management System)
 * API for managing contractors and storage requests
 * OpenAPI spec version: 1.0.0
 */
import type { CargoDetails } from './cargoDetails';
import type { SpecialRequirement } from './specialRequirement';

export interface StorageRequestCreate {
  contractorId?: string;
  contractorName?: string;
  warehouseId?: string;
  entryDate?: string;
  exitDate?: string;
  cargoDetails?: CargoDetails;
  specialRequirements?: SpecialRequirement[];
  specialHandlingInstructions?: string;
}
