import type { Shipment } from './shipment.model'

export const mockShipments: Shipment[] = [
  {
    id: 'SH-2024-001',
    shipmentNumber: 'SH-2024-001',
    type: 'SHIPMENT',
    status: 'IN_TRANSIT' as any,
    priority: 'NORMAL' as any,
    pickupLocation: {
      address: { city: 'Warsaw', country: 'Poland', street: 'ul. Logistyczna 123', postalCode: '00-001' },
      contactPerson: 'John Doe',
      contactPhone: '+48123456789',
      contactEmail: 'john@example.com',
      operatingHours: {} as any,
      loadingType: 'DOCK' as any,
      facilityType: 'WAREHOUSE' as any
    },
    deliveryLocation: {
      address: { city: 'Berlin', country: 'Germany', street: 'Hauptstraße 456', postalCode: '10115' },
      contactPerson: 'Jane Smith',
      contactPhone: '+49123456789',
      contactEmail: 'jane@example.com',
      operatingHours: {} as any,
      loadingType: 'DOCK' as any,
      facilityType: 'WAREHOUSE' as any
    },
    cargo: {} as any,
    serviceType: 'FULL_TRUCKLOAD' as any,
    vehicleRequirements: {} as any,
    scheduledPickupDate: new Date('2024-01-15'),
    scheduledDeliveryDate: new Date('2024-01-17'),
    actualPickupDate: new Date('2024-01-15'),
    requiresInsurance: true,
    requiresCustomsClearance: false,
    currency: 'EUR',
    trackingNumber: 'TRK123456789',
    progressUpdates: [],
    createdBy: '1',
    companyId: '1',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'SH-2024-002',
    shipmentNumber: 'SH-2024-002',
    type: 'SHIPMENT',
    status: 'DELIVERED' as any,
    priority: 'HIGH' as any,
    pickupLocation: {
      address: { city: 'Krakow', country: 'Poland', street: 'ul. Przemysłowa 789', postalCode: '30-001' },
      contactPerson: 'Anna Kowalski',
      contactPhone: '+48987654321',
      contactEmail: 'anna@example.com',
      operatingHours: {} as any,
      loadingType: 'GROUND' as any,
      facilityType: 'FACTORY' as any
    },
    deliveryLocation: {
      address: { city: 'Vienna', country: 'Austria', street: 'Industriestraße 321', postalCode: '1010' },
      contactPerson: 'Hans Mueller',
      contactPhone: '+43123456789',
      contactEmail: 'hans@example.com',
      operatingHours: {} as any,
      loadingType: 'DOCK' as any,
      facilityType: 'WAREHOUSE' as any
    },
    cargo: {} as any,
    serviceType: 'EXPRESS_DELIVERY' as any,
    vehicleRequirements: {} as any,
    scheduledPickupDate: new Date('2024-01-12'),
    scheduledDeliveryDate: new Date('2024-01-13'),
    actualPickupDate: new Date('2024-01-12'),
    actualDeliveryDate: new Date('2024-01-13'),
    requiresInsurance: true,
    requiresCustomsClearance: false,
    currency: 'EUR',
    trackingNumber: 'TRK987654321',
    progressUpdates: [],
    createdBy: '1',
    companyId: '1',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'SH-2024-003',
    shipmentNumber: 'SH-2024-003',
    type: 'SHIPMENT',
    status: 'PICKUP_SCHEDULED' as any,
    priority: 'NORMAL' as any,
    pickupLocation: {
      address: { city: 'Prague', country: 'Czech Republic', street: 'Průmyslová 555', postalCode: '110 00' },
      contactPerson: 'Pavel Novák',
      contactPhone: '+420123456789',
      contactEmail: 'pavel@example.com',
      operatingHours: {} as any,
      loadingType: 'CRANE' as any,
      facilityType: 'WAREHOUSE' as any
    },
    deliveryLocation: {
      address: { city: 'Hamburg', country: 'Germany', street: 'Hafenstraße 888', postalCode: '20095' },
      contactPerson: 'Klaus Weber',
      contactPhone: '+49987654321',
      contactEmail: 'klaus@example.com',
      operatingHours: {} as any,
      loadingType: 'DOCK' as any,
      facilityType: 'PORT' as any
    },
    cargo: {} as any,
    serviceType: 'OVERSIZED_CARGO' as any,
    vehicleRequirements: {} as any,
    scheduledPickupDate: new Date('2024-01-18'),
    scheduledDeliveryDate: new Date('2024-01-20'),
    requiresInsurance: true,
    requiresCustomsClearance: false,
    currency: 'EUR',
    trackingNumber: 'TRK456789123',
    progressUpdates: [],
    createdBy: '1',
    companyId: '1',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'SH-2024-004',
    shipmentNumber: 'SH-2024-004',
    type: 'SHIPMENT',
    status: 'OUT_FOR_DELIVERY' as any,
    priority: 'URGENT' as any,
    pickupLocation: {
      address: { city: 'Budapest', country: 'Hungary', street: 'Ipari út 222', postalCode: '1117' },
      contactPerson: 'László Kovács',
      contactPhone: '+36123456789',
      contactEmail: 'laszlo@example.com',
      operatingHours: {} as any,
      loadingType: 'FORKLIFT' as any,
      facilityType: 'WAREHOUSE' as any
    },
    deliveryLocation: {
      address: { city: 'Amsterdam', country: 'Netherlands', street: 'Industrieweg 777', postalCode: '1043 AP' },
      contactPerson: 'Jan van der Berg',
      contactPhone: '+31123456789',
      contactEmail: 'jan@example.com',
      operatingHours: {} as any,
      loadingType: 'DOCK' as any,
      facilityType: 'DISTRIBUTION_CENTER' as any
    },
    cargo: {} as any,
    serviceType: 'EXPRESS_DELIVERY' as any,
    vehicleRequirements: {} as any,
    scheduledPickupDate: new Date('2024-01-16'),
    scheduledDeliveryDate: new Date('2024-01-17'),
    actualPickupDate: new Date('2024-01-16'),
    requiresInsurance: true,
    requiresCustomsClearance: false,
    currency: 'EUR',
    trackingNumber: 'TRK789123456',
    progressUpdates: [],
    createdBy: '1',
    companyId: '1',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'SH-2024-005',
    shipmentNumber: 'SH-2024-005',
    type: 'SHIPMENT',
    status: 'COMPLETED' as any,
    priority: 'NORMAL' as any,
    pickupLocation: {
      address: { city: 'Gdansk', country: 'Poland', street: 'ul. Portowa 111', postalCode: '80-001' },
      contactPerson: 'Marek Wiśniewski',
      contactPhone: '+48555666777',
      contactEmail: 'marek@example.com',
      operatingHours: {} as any,
      loadingType: 'DOCK' as any,
      facilityType: 'PORT' as any
    },
    deliveryLocation: {
      address: { city: 'Stockholm', country: 'Sweden', street: 'Industrivägen 999', postalCode: '111 60' },
      contactPerson: 'Erik Andersson',
      contactPhone: '+46123456789',
      contactEmail: 'erik@example.com',
      operatingHours: {} as any,
      loadingType: 'GROUND' as any,
      facilityType: 'WAREHOUSE' as any
    },
    cargo: {} as any,
    serviceType: 'FULL_TRUCKLOAD' as any,
    vehicleRequirements: {} as any,
    scheduledPickupDate: new Date('2024-01-10'),
    scheduledDeliveryDate: new Date('2024-01-14'),
    actualPickupDate: new Date('2024-01-10'),
    actualDeliveryDate: new Date('2024-01-14'),
    requiresInsurance: false,
    requiresCustomsClearance: true,
    currency: 'EUR',
    trackingNumber: 'TRK321654987',
    progressUpdates: [],
    createdBy: '1',
    companyId: '1',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'SH-2024-006',
    shipmentNumber: 'SH-2024-006',
    type: 'SHIPMENT',
    status: 'AWAITING_PAYMENT' as any,
    priority: 'HIGH' as any,
    pickupLocation: {
      address: { city: 'Bratislava', country: 'Slovakia', street: 'Priemyselná 333', postalCode: '821 09' },
      contactPerson: 'Michal Horváth',
      contactPhone: '+421123456789',
      contactEmail: 'michal@example.com',
      operatingHours: {} as any,
      loadingType: 'DOCK' as any,
      facilityType: 'FACTORY' as any
    },
    deliveryLocation: {
      address: { city: 'Milan', country: 'Italy', street: 'Via Industriale 444', postalCode: '20100' },
      contactPerson: 'Marco Rossi',
      contactPhone: '+39123456789',
      contactEmail: 'marco@example.com',
      operatingHours: {} as any,
      loadingType: 'FORKLIFT' as any,
      facilityType: 'WAREHOUSE' as any
    },
    cargo: {} as any,
    serviceType: 'LESS_THAN_TRUCKLOAD' as any,
    vehicleRequirements: {} as any,
    scheduledPickupDate: new Date('2024-01-14'),
    scheduledDeliveryDate: new Date('2024-01-16'),
    actualPickupDate: new Date('2024-01-14'),
    actualDeliveryDate: new Date('2024-01-16'),
    requiresInsurance: true,
    requiresCustomsClearance: false,
    currency: 'EUR',
    trackingNumber: 'TRK654987321',
    progressUpdates: [],
    createdBy: '1',
    companyId: '1',
    createdAt: new Date(),
    updatedAt: new Date()
  },
  {
    id: 'SH-2024-007',
    shipmentNumber: 'SH-2024-007',
    type: 'SHIPMENT',
    status: 'PAID' as any,
    priority: 'LOW' as any,
    pickupLocation: {
      address: { city: 'Lyon', country: 'France', street: 'Rue Industrielle 555', postalCode: '69000' },
      contactPerson: 'Pierre Dubois',
      contactPhone: '+33123456789',
      contactEmail: 'pierre@example.com',
      operatingHours: {} as any,
      loadingType: 'DOCK' as any,
      facilityType: 'WAREHOUSE' as any
    },
    deliveryLocation: {
      address: { city: 'Barcelona', country: 'Spain', street: 'Carrer Industrial 777', postalCode: '08001' },
      contactPerson: 'Carlos García',
      contactPhone: '+34123456789',
      contactEmail: 'carlos@example.com',
      operatingHours: {} as any,
      loadingType: 'GROUND' as any,
      facilityType: 'DISTRIBUTION_CENTER' as any
    },
    cargo: {} as any,
    serviceType: 'FULL_TRUCKLOAD' as any,
    vehicleRequirements: {} as any,
    scheduledPickupDate: new Date('2024-01-08'),
    scheduledDeliveryDate: new Date('2024-01-12'),
    actualPickupDate: new Date('2024-01-08'),
    actualDeliveryDate: new Date('2024-01-12'),
    requiresInsurance: true,
    requiresCustomsClearance: false,
    currency: 'EUR',
    trackingNumber: 'TRK888999111',
    progressUpdates: [],
    createdBy: '1',
    companyId: '1',
    createdAt: new Date(),
    updatedAt: new Date()
  }
] 