package generator

const banner = `
-- SQL generated by tms-data-generator
-- DO NOT EDIT THIS FILE MANUALLY
-- Edit the create-tms-schema.sql file instead
--
-- 🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚
-- 🚚 DELIVEROO (C) 2025 🚚
-- 🚚   SHIP THAT SHIT   🚚
-- 🚚   Spółka Akcyjna   🚚
-- 🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚🚚
--
-- Zatrudniamy! https://shorturl.at/G98Ej
`
