import type { WarehousingRequestItem } from './warehousing-requests.model'

export const mockWarehousingRequests: WarehousingRequestItem[] = [
  {
    id: 'WH-2024-005',
    requestNumber: 'WH-2024-005',
    type: 'Warehousing',
    status: 'SUBMITTED',
    details: 'Hazardous Storage',
    subDetails: 'Chemical products - 30 m³',
    date: new Date('2024-01-24'),
    priority: 'URGENT',
    trackingNumber: undefined,
    storageType: 'HAZARDOUS',
    securityLevel: 'MAXIMUM',
    volume: 30
  },
  {
    id: 'WH-2024-007',
    requestNumber: 'WH-2024-007',
    type: 'Warehousing',
    status: 'UNDER_REVIEW',
    details: 'Climate Controlled Storage',
    subDetails: 'Medical supplies - 45 m³',
    date: new Date('2024-01-23'),
    priority: 'HIGH',
    trackingNumber: undefined,
    storageType: 'CLIMATE_CONTROLLED',
    securityLevel: 'HIGH',
    volume: 45
  },
  {
    id: 'WH-2024-008',
    requestNumber: 'WH-2024-008',
    type: 'Warehousing',
    status: 'APPROVED',
    details: 'Ambient Storage',
    subDetails: 'General cargo - 80 m³',
    date: new Date('2024-01-22'),
    priority: 'NORMAL',
    trackingNumber: undefined,
    storageType: 'AMBIENT',
    securityLevel: 'STANDARD',
    volume: 80
  },
  {
    id: 'WH-2024-009',
    requestNumber: 'WH-2024-009',
    type: 'Warehousing',
    status: 'PENDING_ARRIVAL',
    details: 'Refrigerated Storage',
    subDetails: 'Fresh products - 35 m³',
    date: new Date('2024-01-21'),
    priority: 'HIGH',
    trackingNumber: undefined,
    storageType: 'REFRIGERATED',
    securityLevel: 'STANDARD',
    volume: 35
  },
  {
    id: 'WH-2024-010',
    requestNumber: 'WH-2024-010',
    type: 'Warehousing',
    status: 'SUBMITTED',
    details: 'Frozen Storage',
    subDetails: 'Frozen foods - 25 m³',
    date: new Date('2024-01-25'),
    priority: 'NORMAL',
    trackingNumber: undefined,
    storageType: 'FROZEN',
    securityLevel: 'STANDARD',
    volume: 25
  },
  {
    id: 'WH-2024-011',
    requestNumber: 'WH-2024-011',
    type: 'Warehousing',
    status: 'RECEIVED',
    details: 'Secure Storage',
    subDetails: 'Valuable items - 15 m³',
    date: new Date('2024-01-20'),
    priority: 'HIGH',
    trackingNumber: undefined,
    storageType: 'SECURE',
    securityLevel: 'MAXIMUM',
    volume: 15
  },
  {
    id: 'WH-2024-012',
    requestNumber: 'WH-2024-012',
    type: 'Warehousing',
    status: 'STORED',
    details: 'Ambient Storage',
    subDetails: 'Textiles - 60 m³',
    date: new Date('2024-01-19'),
    priority: 'LOW',
    trackingNumber: undefined,
    storageType: 'AMBIENT',
    securityLevel: 'STANDARD',
    volume: 60
  },
  {
    id: 'WH-2024-013',
    requestNumber: 'WH-2024-013',
    type: 'Warehousing',
    status: 'COMPLETED',
    details: 'Refrigerated Storage',
    subDetails: 'Pharmaceuticals - 20 m³',
    date: new Date('2024-01-18'),
    priority: 'URGENT',
    trackingNumber: undefined,
    storageType: 'REFRIGERATED',
    securityLevel: 'HIGH',
    volume: 20
  }
] 