/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WMS API (Warehouse Management System)
 * API for managing contractors and storage requests
 * OpenAPI spec version: 1.0.0
 */

export type ContractorStatus = typeof ContractorStatus[keyof typeof ContractorStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ContractorStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
} as const;
