/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * WMS API (Warehouse Management System)
 * API for managing contractors and storage requests
 * OpenAPI spec version: 1.0.0
 */

export type SpecialRequirement = typeof SpecialRequirement[keyof typeof SpecialRequirement];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SpecialRequirement = {
  REQUIRED_REFRIGERATION: 'REQUIRED_REFRIGERATION',
  REQUIRED_FREEZING: 'REQUIRED_FREEZING',
  CONTAINS_HAZMAT: 'CONTAINS_HAZMAT',
  CONTAINS_PERISHABLES: 'CONTAINS_PERISHABLES',
} as const;
