# coding: utf-8

"""
    WMS API (Warehouse Management System)

    API for managing contractors and storage requests

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from contract.address_details import AddressDetails
from contract.contact import Contact
from contract.contractor_status import ContractorStatus
from contract.employee_summary import EmployeeSummary
from typing import Optional, Set
from typing_extensions import Self

class ContractorDetails(BaseModel):
    """
    ContractorDetails
    """ # noqa: E501
    id: StrictStr
    name: StrictStr
    status: ContractorStatus
    tax_id_number: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    contacts: List[Contact]
    addresses: List[AddressDetails]
    employees: List[EmployeeSummary]
    __properties: ClassVar[List[str]] = ["id", "name", "status", "tax_id_number", "created_at", "updated_at", "contacts", "addresses", "employees"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ContractorDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=False,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in contacts (list)
        _items = []
        if self.contacts:
            for _item_contacts in self.contacts:
                if _item_contacts:
                    _items.append(_item_contacts.to_dict())
            _dict['contacts'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in addresses (list)
        _items = []
        if self.addresses:
            for _item_addresses in self.addresses:
                if _item_addresses:
                    _items.append(_item_addresses.to_dict())
            _dict['addresses'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in employees (list)
        _items = []
        if self.employees:
            for _item_employees in self.employees:
                if _item_employees:
                    _items.append(_item_employees.to_dict())
            _dict['employees'] = _items
        # set to None if tax_id_number (nullable) is None
        # and model_fields_set contains the field
        if self.tax_id_number is None and "tax_id_number" in self.model_fields_set:
            _dict['tax_id_number'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ContractorDetails from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "tax_id_number": obj.get("tax_id_number"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "contacts": [Contact.from_dict(_item) for _item in obj["contacts"]] if obj.get("contacts") is not None else None,
            "addresses": [AddressDetails.from_dict(_item) for _item in obj["addresses"]] if obj.get("addresses") is not None else None,
            "employees": [EmployeeSummary.from_dict(_item) for _item in obj["employees"]] if obj.get("employees") is not None else None
        })
        return _obj


