# coding: utf-8

"""
    WMS API (Warehouse Management System)

    API for managing contractors and storage requests

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from contract.cargo_details import CargoDetails
from contract.special_requirement import SpecialRequirement
from typing import Optional, Set
from typing_extensions import Self

class StorageRequestCreate(BaseModel):
    """
    StorageRequestCreate
    """ # noqa: E501
    contractor_id: Optional[StrictStr] = Field(default=None, alias="contractorId")
    contractor_name: Optional[StrictStr] = Field(default=None, alias="contractorName")
    warehouse_id: Optional[StrictStr] = Field(default=None, alias="warehouseId")
    entry_date: Optional[date] = Field(default=None, alias="entryDate")
    exit_date: Optional[date] = Field(default=None, alias="exitDate")
    cargo_details: Optional[CargoDetails] = Field(default=None, alias="cargoDetails")
    special_requirements: Optional[List[SpecialRequirement]] = Field(default=None, alias="specialRequirements")
    special_handling_instructions: Optional[StrictStr] = Field(default=None, alias="specialHandlingInstructions")
    __properties: ClassVar[List[str]] = ["contractorId", "contractorName", "warehouseId", "entryDate", "exitDate", "cargoDetails", "specialRequirements", "specialHandlingInstructions"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of StorageRequestCreate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=False,
        )
        # override the default output from pydantic by calling `to_dict()` of cargo_details
        if self.cargo_details:
            _dict['cargoDetails'] = self.cargo_details.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of StorageRequestCreate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "contractorId": obj.get("contractorId"),
            "contractorName": obj.get("contractorName"),
            "warehouseId": obj.get("warehouseId"),
            "entryDate": obj.get("entryDate"),
            "exitDate": obj.get("exitDate"),
            "cargoDetails": CargoDetails.from_dict(obj["cargoDetails"]) if obj.get("cargoDetails") is not None else None,
            "specialRequirements": obj.get("specialRequirements"),
            "specialHandlingInstructions": obj.get("specialHandlingInstructions")
        })
        return _obj


