"""
Seed data for TMS API - matches frontend Vehicle and Driver shapes.
Uses string IDs and JSON-serializable formats (ISO date strings).
"""

VEHICLES = [
    {
        "id": "vehicle-001",
        "plateNumber": "WA-LOG 2024",
        "make": "Mercedes-Benz",
        "model": "Actros 1851",
        "year": 2022,
        "type": "standard",
        "status": "available",
        "mileage": 125000,
        "capacity": {"weight": 26, "volume": 90},
        "cargoTypes": ["ogólne", "paletowe", "suche"],
        "currentDriver": "Jan Kowalski",
        "currentLocation": {
            "lat": 52.2297,
            "lng": 21.0122,
            "address": "Centrum Dystrybucji Warszawa",
        },
        "ownership": {
            "type": "owned",
            "purchaseDate": "2022-03-15",
            "purchasePrice": 480000,
        },
        "documents": [
            {
                "id": "doc-001-1",
                "type": "registration",
                "number": "REJ-WA-LOG-2024",
                "issueDate": "2022-03-15",
                "expiryDate": "2025-03-15",
                "issuingAuthority": "Wydział Komunikacji Warszawa",
            },
            {
                "id": "doc-001-2",
                "type": "insurance",
                "number": "UB-001-2024",
                "issueDate": "2024-01-01",
                "expiryDate": "2025-01-01",
                "issuingAuthority": "PZU Ubezpieczenia",
            },
        ],
        "maintenanceHistory": [
            {
                "id": "maint-001-1",
                "date": "2024-10-15T00:00:00.000Z",
                "type": "routine",
                "description": "Przegląd okresowy - wymiana oleju, filtrów",
                "cost": 1800,
                "mileage": 124500,
                "duration": 3,
                "serviceProvider": "Serwis Mercedes Warszawa",
                "technician": "Marek Kowalczyk",
                "status": "completed",
            },
        ],
        "maintenanceTasks": [
            {
                "id": "task-001-1",
                "description": "Wymiana oleju silnikowego",
                "dueDate": "2025-03-01",
                "estimatedCost": 500,
                "estimatedDuration": 2,
                "status": "pending",
                "type": "routine",
                "assignedTo": "Marek Kowalczyk",
            },
        ],
    },
    {
        "id": "vehicle-002",
        "plateNumber": "GD-EX 1234",
        "make": "Volvo",
        "model": "FH16 750",
        "year": 2021,
        "type": "tir",
        "status": "in-transit",
        "mileage": 180000,
        "capacity": {"weight": 40, "volume": 120},
        "cargoTypes": ["ogólne", "paletowe", "międzynarodowe"],
        "currentDriver": "Maria Nowak",
        "currentLocation": {
            "lat": 52.52,
            "lng": 13.405,
            "address": "Berlin, Germany",
        },
        "ownership": {
            "type": "leased",
            "leaseStart": "2021-06-01",
            "leaseEnd": "2026-06-01",
            "monthlyPayment": 11200,
            "leasingCompany": "Volvo Financial Services",
        },
        "documents": [],
        "maintenanceHistory": [],
        "maintenanceTasks": [],
    },
]

DRIVERS = [
    {
        "id": "driver-001",
        "name": "Jan Kowalski",
        "email": "jan.kowalski@deliveroo.pl",
        "phone": "+48 123 456 789",
        "address": {
            "street": "ul. Logistyczna 15",
            "city": "Warszawa",
            "postalCode": "02-001",
            "country": "Polska",
        },
        "contractType": "full-time",
        "salary": 8500,
        "currency": "PLN",
        "licenseNumber": "DL-123456",
        "licenseExpiry": "2026-05-15",
        "hireDate": "2020-03-01",
        "status": "active",
        "emergencyContact": {
            "name": "Anna Kowalska",
            "phone": "+48 987 654 321",
            "relationship": "spouse",
        },
        "routes": [],
        "calendarEvents": [],
    },
    {
        "id": "driver-002",
        "name": "Maria Nowak",
        "email": "maria.nowak@deliveroo.pl",
        "phone": "+48 234 567 890",
        "address": {
            "street": "ul. Transportowa 8",
            "city": "Gdańsk",
            "postalCode": "80-001",
            "country": "Polska",
        },
        "contractType": "contractor",
        "salary": 9200,
        "currency": "PLN",
        "licenseNumber": "DL-234567",
        "licenseExpiry": "2025-12-20",
        "hireDate": "2019-06-15",
        "status": "on-route",
        "emergencyContact": {
            "name": "Piotr Nowak",
            "phone": "+48 876 543 210",
            "relationship": "spouse",
        },
        "routes": [],
        "calendarEvents": [],
    },
]
